<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExtentReports" Version="5.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Microsoft.Playwright.NUnit" Version="1.49.0" />
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
		<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="json\data.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	<PropertyGroup>
		
		<PlaywrightPlatform>chromium</PlaywrightPlatform>
		<CopyPlaywrightToOutputDirectory>true</CopyPlaywrightToOutputDirectory>
	</PropertyGroup>

</Project>
